/* ============================================================
   Quotely — Random Quote Generator
   quotes.js
   Curated list of unique inspirational, motivational, success,
   education, and life quotes.
   ============================================================ */

window.QUOTELY_QUOTES = [
    // --- Inspirational ---
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Inspirational" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Inspirational" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Inspirational" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Inspirational" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", category: "Inspirational" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "Inspirational" },
    { text: "Your limitation\u2014it's only your imagination.", author: "Unknown", category: "Inspirational" },
    { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown", category: "Inspirational" },
    { text: "Great things never come from comfort zones.", author: "Unknown", category: "Inspirational" },
    { text: "Dream it. Wish it. Do it.", author: "Unknown", category: "Inspirational" },
    { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown", category: "Inspirational" },
    { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown", category: "Inspirational" },
    { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown", category: "Inspirational" },
    { text: "Little things make big days.", author: "Unknown", category: "Inspirational" },
    { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown", category: "Inspirational" },
    { text: "What we think, we become.", author: "Buddha", category: "Inspirational" },
    { text: "The mind is everything. What you think you become.", author: "Buddha", category: "Inspirational" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "Inspirational" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "Inspirational" },
    { text: "An unexamined life is not worth living.", author: "Socrates", category: "Inspirational" },

    // --- Motivational ---
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "Motivational" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Motivational" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "Motivational" },
    { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", category: "Motivational" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", category: "Motivational" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "Motivational" },
    { text: "If you're going through hell, keep going.", author: "Winston Churchill", category: "Motivational" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", category: "Motivational" },
    { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou", category: "Motivational" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", category: "Motivational" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Motivational" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Motivational" },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "Motivational" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", category: "Motivational" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", category: "Motivational" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Motivational" },
    { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", category: "Motivational" },
    { text: "You learn more from failure than from success. Don't let it stop you.", author: "Unknown", category: "Motivational" },
    { text: "Experience is a hard teacher because she gives the test first, the lesson afterward.", author: "Vernon Sanders Law", category: "Motivational" },
    { text: "Risk more than others think is safe. Dream more than others think is practical.", author: "Howard Schultz", category: "Motivational" },

    // --- Success ---
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "Success" },
    { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis", category: "Success" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", category: "Success" },
    { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison", category: "Success" },
    { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs", category: "Success" },
    { text: "The number one reason people fail in life is because they listen to their friends, family, and neighbors.", author: "Napoleon Hill", category: "Success" },
    { text: "The secret of success is to do the common things uncommonly well.", author: "John D. Rockefeller", category: "Success" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer", category: "Success" },
    { text: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein", category: "Success" },
    { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", category: "Success" },
    { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou", category: "Success" },
    { text: "Don't aim for success if you want it; just do what you love and believe in, and it will come naturally.", author: "David Frost", category: "Success" },
    { text: "Success seems to be connected with action. Successful people keep moving.", author: "Conrad Hilton", category: "Success" },

    // --- Education ---
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", category: "Education" },
    { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King", category: "Education" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", category: "Education" },
    { text: "Education is not the filling of a pail, but the lighting of a fire.", author: "William Butler Yeats", category: "Education" },
    { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", category: "Education" },
    { text: "Develop a passion for learning. If you do, you will never cease to grow.", author: "Anthony J. D'Angelo", category: "Education" },
    { text: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein", category: "Education" },
    { text: "The whole purpose of education is to turn mirrors into windows.", author: "Sydney J. Harris", category: "Education" },
    { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", category: "Education" },
    { text: "Change is the end result of all true learning.", author: "Leo Buscaglia", category: "Education" },
    { text: "Education is not preparation for life; education is life itself.", author: "John Dewey", category: "Education" },
    { text: "The aim of education is the knowledge, not of facts, but of values.", author: "William S. Burroughs", category: "Education" },
    { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci", category: "Education" },
    { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch", category: "Education" },
    { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin", category: "Education" },

    // --- Life ---
    { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "Life" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", category: "Life" },
    { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", category: "Life" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", category: "Life" },
    { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll", category: "Life" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu", category: "Life" },
    { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", category: "Life" },
    { text: "You cannot swim for new horizons until you have courage to lose sight of the shore.", author: "William Faulkner", category: "Life" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "Life" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Life" },
    { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany", category: "Life" },
    { text: "Get busy living or get busy dying.", author: "Stephen King", category: "Life" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West", category: "Life" },
    { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost", category: "Life" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller", category: "Life" },
    { text: "To live is the rarest thing in the world. Most people just exist.", author: "Oscar Wilde", category: "Life" },
    { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw", category: "Life" },
    { text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain", category: "Life" },
    { text: "Keep smiling, because life is a beautiful thing and there's so much to smile about.", author: "Marilyn Monroe", category: "Life" },

    // --- Wisdom / Mindset ---
    { text: "Quality is not an act, it is a habit.", author: "Aristotle", category: "Wisdom" },
    { text: "Well done is better than well said.", author: "Benjamin Franklin", category: "Wisdom" },
    { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", category: "Wisdom" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "Wisdom" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", category: "Wisdom" },
    { text: "Stay hungry, stay foolish.", author: "Stewart Brand", category: "Wisdom" },
    { text: "Wisdom begins in wonder.", author: "Socrates", category: "Wisdom" },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Wisdom" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "Wisdom" },
    { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", category: "Wisdom" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle", category: "Wisdom" },
    { text: "It is not what happens to you, but how you react to it that matters.", author: "Epictetus", category: "Wisdom" },
    { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", category: "Wisdom" },
    { text: "The journey not the arrival matters.", author: "T.S. Eliot", category: "Wisdom" },
    { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", category: "Wisdom" },

    // --- Creativity / Courage ---
    { text: "Creativity is intelligence having fun.", author: "Albert Einstein", category: "Creativity" },
    { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou", category: "Creativity" },
    { text: "Imagination is more important than knowledge.", author: "Albert Einstein", category: "Creativity" },
    { text: "Every child is an artist. The problem is how to remain an artist once we grow up.", author: "Pablo Picasso", category: "Creativity" },
    { text: "Creativity takes courage.", author: "Henri Matisse", category: "Creativity" },
    { text: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain", category: "Courage" },
    { text: "Fortune favors the brave.", author: "Virgil", category: "Courage" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt", category: "Courage" },
];